export enum StatusService {
  Requested = "Requested",
  InAnalysis = "InAnalysis",
  AwaitingClarifications = "AwaitingClarifications",
  QuoteSent = "QuoteSent",
  AwaitingQuoteApproval = "AwaitingQuoteApproval",
  QuoteApproved = "QuoteApproved",
  QuoteRejected = "QuoteRejected",
  AwaitingExecutionDate = "AwaitingExecutionDate",
  DateProposedByAdmin = "DateProposedByAdmin",
  AwaitingDateApproval = "AwaitingDateApproval",
  DateApprovedByClient = "DateApprovedByClient",
  DateRejectedByClient = "DateRejectedByClient",
  SearchingProfessional = "SearchingProfessional",
  ProfessionalSelected = "ProfessionalSelected",
  AwaitingProfessionalConfirmation = "AwaitingProfessionalConfirmation",
  Scheduled = "Scheduled",
  InProgress = "InProgress",
  CompletedAwaitingApproval = "CompletedAwaitingApproval",
  Cancelled = "Cancelled",
}
